import type { Newsletter } from "@/types";

export const MOCK_NEWSLETTERS: Newsletter[] = [
  {
    id: "1",
    userId: "mock-user",
    messageId: "msg-001",
    sender: "hello@tldr.tech",
    senderName: "TLDR",
    subject: "TLDR: OpenAI launches GPT-5, Apple Vision Pro sales slow down",
    receivedAt: new Date("2026-02-06T08:00:00Z"),
    htmlBody: null,
    plainText: null,
    viewInBrowserLink: "https://tldr.tech/issue/1234",
    summary:
      "OpenAI announced GPT-5 with breakthrough reasoning capabilities. Apple Vision Pro sees declining quarterly sales after initial launch hype. Google releases Gemini 2.0 Flash for developers with generous free tier.",
    topics: ["ai", "tech"],
    isRead: true,
    processedAt: new Date("2026-02-06T08:01:00Z"),
    createdAt: new Date("2026-02-06T08:01:00Z"),
  },
  {
    id: "2",
    userId: "mock-user",
    messageId: "msg-002",
    sender: "digest@morningbrew.com",
    senderName: "Morning Brew",
    subject: "The Fed holds rates steady, crypto market rallies hard",
    receivedAt: new Date("2026-02-05T07:30:00Z"),
    htmlBody: null,
    plainText: null,
    viewInBrowserLink: "https://morningbrew.com/daily/issue/5678",
    summary:
      "Federal Reserve keeps interest rates unchanged at 4.5%. Bitcoin surges past $120k on renewed institutional ETF inflows. Amazon reports record Q4 earnings, beating Wall Street expectations by 12%.",
    topics: ["finance", "business"],
    isRead: false,
    processedAt: new Date("2026-02-05T07:31:00Z"),
    createdAt: new Date("2026-02-05T07:31:00Z"),
  },
  {
    id: "3",
    userId: "mock-user",
    messageId: "msg-003",
    sender: "dan@tldrsec.com",
    senderName: "tl;dr sec",
    subject: "tl;dr sec #230: Zero-day exploits surge, new NIST framework",
    receivedAt: new Date("2026-02-04T10:00:00Z"),
    htmlBody: null,
    plainText: null,
    viewInBrowserLink: "https://tldrsec.com/issue/230",
    summary:
      "Critical zero-day exploits targeting enterprise VPNs increased 40% in January. NIST releases updated cybersecurity framework v2.1. Major cloud providers announce shared threat intelligence alliance.",
    topics: ["security", "tech"],
    isRead: true,
    processedAt: new Date("2026-02-04T10:01:00Z"),
    createdAt: new Date("2026-02-04T10:01:00Z"),
  },
  {
    id: "4",
    userId: "mock-user",
    messageId: "msg-004",
    sender: "hello@densediscovery.com",
    senderName: "Dense Discovery",
    subject: "Dense Discovery #321: The state of design systems in 2026",
    receivedAt: new Date("2026-02-03T09:00:00Z"),
    htmlBody: null,
    plainText: null,
    viewInBrowserLink: "https://densediscovery.com/issues/321",
    summary:
      "Design systems are evolving with AI-assisted component generation. New tools bridge the gap between Figma and code. Accessibility-first design becomes the default approach across major platforms.",
    topics: ["design", "tech"],
    isRead: false,
    processedAt: new Date("2026-02-03T09:01:00Z"),
    createdAt: new Date("2026-02-03T09:01:00Z"),
  },
  {
    id: "5",
    userId: "mock-user",
    messageId: "msg-005",
    sender: "team@producthunt.com",
    senderName: "Product Hunt",
    subject: "Product Hunt Daily: Top 5 launches this week",
    receivedAt: new Date("2026-02-02T14:00:00Z"),
    htmlBody: null,
    plainText: null,
    viewInBrowserLink: "https://producthunt.com/newsletter/feb-02",
    summary:
      "This week's top launches include an AI code reviewer, a privacy-focused analytics tool, and a collaborative whiteboard for remote teams. Indie makers are shipping faster with new no-code platforms.",
    topics: ["tech", "productivity"],
    isRead: false,
    processedAt: new Date("2026-02-02T14:01:00Z"),
    createdAt: new Date("2026-02-02T14:01:00Z"),
  },
  {
    id: "6",
    userId: "mock-user",
    messageId: "msg-006",
    sender: "weekly@bitcoinmagazine.com",
    senderName: "Bitcoin Magazine",
    subject: "Weekly Digest: Institutional adoption accelerates",
    receivedAt: new Date("2026-02-01T12:00:00Z"),
    htmlBody: null,
    plainText: null,
    viewInBrowserLink: "https://bitcoinmagazine.com/weekly/feb-01",
    summary:
      "Major pension funds allocate 2-5% to Bitcoin. Lightning Network processes record 1M daily transactions. El Salvador's Bitcoin bonds outperform traditional sovereign debt instruments significantly.",
    topics: ["crypto", "finance"],
    isRead: true,
    processedAt: new Date("2026-02-01T12:01:00Z"),
    createdAt: new Date("2026-02-01T12:01:00Z"),
  },
  {
    id: "7",
    userId: "mock-user",
    messageId: "msg-007",
    sender: "hello@bytebytego.com",
    senderName: "ByteByteGo",
    subject: "System Design: How Netflix handles 250M subscribers",
    receivedAt: new Date("2026-01-31T08:00:00Z"),
    htmlBody: null,
    plainText: null,
    viewInBrowserLink: "https://bytebytego.com/issue/42",
    summary:
      "Deep dive into Netflix's microservices architecture handling 250M users globally. Key patterns include edge caching, adaptive bitrate streaming, and chaos engineering for resilience at massive scale.",
    topics: ["tech", "ai"],
    isRead: false,
    processedAt: new Date("2026-01-31T08:01:00Z"),
    createdAt: new Date("2026-01-31T08:01:00Z"),
  },
  {
    id: "8",
    userId: "mock-user",
    messageId: "msg-008",
    sender: "newsletter@pragmaticengineer.com",
    senderName: "The Pragmatic Engineer",
    subject: "What Silicon Valley layoffs mean for engineering culture",
    receivedAt: new Date("2026-01-30T09:00:00Z"),
    htmlBody: null,
    plainText: null,
    viewInBrowserLink: "https://pragmaticengineer.com/issue/188",
    summary:
      "Tech layoffs reshape engineering culture toward efficiency over growth-at-all-costs. Companies adopt smaller, senior-heavy teams. Remote work policies tighten but hybrid models persist across the industry.",
    topics: ["tech", "business"],
    isRead: false,
    processedAt: new Date("2026-01-30T09:01:00Z"),
    createdAt: new Date("2026-01-30T09:01:00Z"),
  },
];

export const ALL_TOPICS = [
  "ai",
  "tech",
  "finance",
  "business",
  "design",
  "productivity",
  "security",
  "crypto",
] as const;

export type Topic = (typeof ALL_TOPICS)[number];

export const TOPIC_COLORS: Record<Topic, string> = {
  ai: "bg-violet-100 text-violet-800 dark:bg-violet-900 dark:text-violet-200",
  tech: "bg-blue-100 text-blue-800 dark:bg-blue-900 dark:text-blue-200",
  finance:
    "bg-emerald-100 text-emerald-800 dark:bg-emerald-900 dark:text-emerald-200",
  business: "bg-amber-100 text-amber-800 dark:bg-amber-900 dark:text-amber-200",
  design: "bg-pink-100 text-pink-800 dark:bg-pink-900 dark:text-pink-200",
  productivity: "bg-cyan-100 text-cyan-800 dark:bg-cyan-900 dark:text-cyan-200",
  security: "bg-red-100 text-red-800 dark:bg-red-900 dark:text-red-200",
  crypto:
    "bg-orange-100 text-orange-800 dark:bg-orange-900 dark:text-orange-200",
};
